### ISSUE TITLE
Is it for learning or is a production code?

### ISSUE THREAD

**Issue by shahryarjb** [samirghasemi/Snack_Snapp#1]
Hi Dear @samirghasemi,
I was watching your code in the `Snack_Snapp` project, and I saw this part, I am wondering is it for learning, or it is a production code, because I prefer to use Ecto macros and commands instead of a query like this.

https://github.com/samirghasemi/Snack_Snapp/blob/00045ae461252aaf36a3cf00c8daac3f6a458300/lib/snack/accounts.ex#L127-L132

### For example, like this:

```elixir
  def authors(post_id) do
    from(author in BlogAuthor,
    where: author.post_id == ^post_id,
    join: user in assoc(author, :users),
    select: %{
      id: author.id,
      post_id: author.post_id,
      inserted_at: author.inserted_at,
      updated_at: author.updated_at,
      user_id: user.id,
      user_full_name: user.full_name
    })
    |> Repo.all()
  rescue
    db_error ->
      Something ....
  end
```

Thank you

**Comment by samirghasemi** [comment]
hi dear @shahryarjb
this is my final project for course of Takmili(!!!!) in shahid beheshti university
I am agree with you to use macros, but i use Arrango db and me and my friends are developing wrapper for that but it is not completed yet!
thanks for your response!
